steps:
  # ==========================================
  # 1. Build & Push Next.js App
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app'
    waitFor: ['-']
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker build \
          --cache-from asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-app:latest \
          --build-arg NEXT_PUBLIC_SUPABASE_URL=$$NEXT_PUBLIC_SUPABASE_URL \
          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$$NEXT_PUBLIC_SUPABASE_ANON_KEY \
          --build-arg NEXT_PUBLIC_BASE_URL=https://hireneo-ai.xyz \
          -t asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-app:latest \
          .
    secretEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-app'
    waitFor: ['build-app']
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-app:latest']

  # ==========================================
  # 2. Build & Push BullMQ Worker
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-worker'
    waitFor: ['-']
    args: ['build', '--cache-from', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-worker:latest', '-f', 'Dockerfile.worker', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-worker:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-worker'
    waitFor: ['build-worker']
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-worker:latest']

  # ==========================================
  # 3. Deploy App to Cloud Run
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-app'
    waitFor: ['push-app']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hireneo-app'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-app:latest'
      - '--region'
      - 'asia-southeast1'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--vpc-egress'
      - 'private-ranges-only'
      - '--memory'
      - '1Gi'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,UPSTASH_REDIS_URL=upstash-redis-url:latest,OPENAI_API_KEY=openai-api-key:latest,RESEND_API_KEY=resend-api-key:latest,NEXT_PUBLIC_SUPABASE_URL=supabase-url:latest,NEXT_PUBLIC_SUPABASE_ANON_KEY=supabase-anon-key:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-key:latest,POLAR_ACCESS_TOKEN=POLAR_ACCESS_TOKEN:latest,POLAR_PRO_PRODUCT_ID=POLAR_PRO_PRODUCT_ID:latest,POLAR_ENTERPRISE_PRODUCT_ID=POLAR_ENTERPRISE_PRODUCT_ID:latest'

  # ==========================================
  # 4. Deploy Worker to Cloud Run
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-worker'
    waitFor: ['push-worker']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hireneo-worker'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-worker:latest'
      - '--region'
      - 'asia-southeast1'
      - '--no-allow-unauthenticated'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--vpc-egress'
      - 'private-ranges-only'
      - '--memory'
      - '512Mi'
      - '--min-instances'
      - '1'
      # CRITICAL: Worker needs PORT=8080 logic we added to scripts/worker.ts
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,UPSTASH_REDIS_URL=upstash-redis-url:latest,OPENAI_API_KEY=openai-api-key:latest,RESEND_API_KEY=resend-api-key:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-key:latest'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-app:latest'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/hireneo-repo/hireneo-worker:latest'

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/supabase-url/versions/latest
      env: 'NEXT_PUBLIC_SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/supabase-anon-key/versions/latest
      env: 'NEXT_PUBLIC_SUPABASE_ANON_KEY'
